"""Shared editor UI design primitives."""

from engine.editor.ui.animation import AnimationController, ColorLerp, LerpValue, PanelAnimation
from engine.editor.ui.file_picker_render import process_file_picker, render_file_picker
from engine.editor.ui.icons import (
    ICON_ARROW_DOWN,
    ICON_CHECK,
    ICON_CHEVRON_LEFT,
    ICON_CHEVRON_RIGHT,
    ICON_CLOSE,
    ICON_GEAR,
    ICON_MENU,
    ICON_MINUS,
    ICON_PAUSE,
    ICON_PLAY,
    ICON_PLUS,
    ICON_SEARCH,
    ICON_STOP,
    ICON_TRASH,
    draw_icon,
    icon_exists,
)
from engine.editor.ui.input import (
    is_clicked,
    is_clicked_at,
    is_hovered,
    is_hovered_at,
    is_pressed,
    is_pressed_at,
    is_right_clicked,
    is_right_clicked_at,
    mouse_position,
    wheel_delta,
)
from engine.editor.ui.inspector import (
    InspectorGroup,
    InspectorModel,
    build_inspector_model_from_dict,
    infer_property_kind,
)
from engine.editor.ui.inspector_render import InspectorPanel, InspectorWidgetRect
from engine.editor.ui.panels import (
    begin_panel_content,
    draw_editor_panel,
    draw_editor_panel_frame,
    draw_panel_header,
    end_panel_content,
)
from engine.editor.ui.popup_render import process_popup_dialog, render_popup_dialog, render_popup_frame
from engine.editor.ui.property_widgets import (
    CommitContract,
    EditTransaction,
    PropertyDescriptor,
    PropertyEditResult,
    PropertyKind,
)
from engine.editor.ui.scroll import EditorScrollResult, editor_scroll_area
from engine.editor.ui.theme import UNITY_DARK, UNITY_LIGHT, EditorTheme, theme_to_raygui_map
from engine.editor.ui.tree_view import (
    TreeModel,
    TreeNode,
    filter_nodes,
    filter_visible_rows,
    get_entity_type,
    get_type_icon,
    matches_search,
)
from engine.editor.ui.virtual_scroll import VirtualScroll
from engine.editor.ui.widget_state import (
    WidgetResult,
    WidgetState,
    WidgetVisualState,
    resolve_visual_state,
)
from engine.editor.ui.widgets import (
    editor_badge,
    editor_button,
    editor_checkbox,
    editor_icon_button,
    editor_label,
    editor_panel,
    editor_panel_header,
    editor_separator,
    editor_slider_float,
    editor_status_pill,
    editor_tab,
    editor_tab_bar,
    editor_text_field_simple,
    editor_toggle_button,
    raygui_dropdown_bridge,
    raygui_textbox_bridge,
)

__all__ = [
    "AnimationController",
    "ColorLerp",
    "EditorTheme",
    "ICON_ARROW_DOWN",
    "ICON_CHECK",
    "ICON_CHEVRON_LEFT",
    "ICON_CHEVRON_RIGHT",
    "ICON_CLOSE",
    "ICON_GEAR",
    "ICON_MENU",
    "ICON_MINUS",
    "ICON_PAUSE",
    "ICON_PLAY",
    "ICON_PLUS",
    "ICON_SEARCH",
    "ICON_STOP",
    "ICON_TRASH",
    "UNITY_DARK",
    "UNITY_LIGHT",
    "VirtualScroll",
    "EditorScrollResult",
    "EditTransaction",
    "InspectorGroup",
    "InspectorModel",
    "InspectorPanel",
    "InspectorWidgetRect",
    "LerpValue",
    "CommitContract",
    "PropertyDescriptor",
    "PropertyEditResult",
    "PropertyKind",
    "PanelAnimation",
    "TreeModel",
    "TreeNode",
    "WidgetResult",
    "WidgetState",
    "WidgetVisualState",
    "draw_icon",
    "begin_panel_content",
    "build_inspector_model_from_dict",
    "draw_editor_panel",
    "draw_editor_panel_frame",
    "draw_panel_header",
    "editor_badge",
    "editor_button",
    "editor_checkbox",
    "editor_icon_button",
    "editor_label",
    "editor_panel",
    "editor_panel_header",
    "editor_separator",
    "editor_slider_float",
    "editor_status_pill",
    "editor_tab",
    "editor_tab_bar",
    "editor_text_field_simple",
    "editor_toggle_button",
    "editor_scroll_area",
    "end_panel_content",
    "filter_nodes",
    "filter_visible_rows",
    "get_entity_type",
    "get_type_icon",
    "icon_exists",
    "infer_property_kind",
    "is_clicked",
    "is_clicked_at",
    "is_hovered",
    "is_hovered_at",
    "is_pressed",
    "is_pressed_at",
    "is_right_clicked",
    "is_right_clicked_at",
    "mouse_position",
    "matches_search",
    "process_file_picker",
    "process_popup_dialog",
    "render_file_picker",
    "render_popup_dialog",
    "render_popup_frame",
    "raygui_dropdown_bridge",
    "raygui_textbox_bridge",
    "resolve_visual_state",
    "theme_to_raygui_map",
    "wheel_delta",
]
