"""Pure editor UI core namespace.

This package contains serializable, renderer-independent editor UI models and
helpers. It must not import pyray or impure ``engine.editor.ui`` modules.
"""

from engine.editor.ui_core.colors import (
    int_to_rgba,
    is_dark_theme,
    lerp_color,
    rgba,
    rgba_to_hex,
    rgba_to_int,
    with_alpha,
)
from engine.editor.ui_core.controls import (
    Anchor,
    Button,
    Container,
    Control,
    ControlEvent,
    ControlEventKind,
    FocusManager,
    HBoxContainer,
    Label,
    LayoutDirection,
    Margin,
    Panel,
    ScrollContainer,
    Size,
    TextureRect,
    VBoxContainer,
)
from engine.editor.ui_core.geometry import (
    Rect,
    clamp_rect,
    inset_rect,
    rect_contains,
    split_bottom,
    split_left,
    split_right,
    split_top,
)
from engine.editor.ui_core.inspector import (
    InspectorGroup,
    InspectorModel,
    build_inspector_model_from_dict,
    infer_property_kind,
)
from engine.editor.ui_core.property_widgets import (
    EditTransaction,
    PropertyDescriptor,
    PropertyEditResult,
    PropertyKind,
)
from engine.editor.ui_core.protocols import EntityLike, PropertyValue, WorldLike
from engine.editor.ui_core.theme import UNITY_DARK, EditorTheme, theme_to_raygui_map
from engine.editor.ui_core.tokens import (
    BG_RAYGUI_DARK,
    BUTTON_RADIUS,
    CONTROL_PADDING_X,
    CONTROL_PADDING_Y,
    EDITOR_ACCENT,
    EDITOR_ACCENT_HOVER,
    EDITOR_BG,
    EDITOR_BORDER,
    EDITOR_BORDER_HOVER,
    EDITOR_DANGER,
    EDITOR_PANEL,
    EDITOR_PANEL_ALT,
    EDITOR_PANEL_HEADER,
    EDITOR_SUCCESS,
    EDITOR_TEXT,
    EDITOR_TEXT_DISABLED,
    EDITOR_TEXT_MUTED,
    EDITOR_WARNING,
    FONT_SIZE_LG,
    FONT_SIZE_MD,
    FONT_SIZE_SM,
    ICON_SIZE_MD,
    ICON_SIZE_SM,
    PANEL_PADDING,
    PANEL_RADIUS,
    RGBA,
    ROW_HEIGHT,
    SPLITTER_WIDTH,
    TAB_HEIGHT,
    TOOLBAR_HEIGHT,
)
from engine.editor.ui_core.tree_view import (
    TreeModel,
    TreeNode,
    filter_nodes,
    filter_visible_rows,
    get_entity_type,
    get_type_icon,
    matches_search,
)
from engine.editor.ui_core.widget_state import (
    WidgetResult,
    WidgetState,
    WidgetVisualState,
    resolve_visual_state,
)

UI_CORE_CONTRACT = {
    "name": "ui_core",
    "schema_version": 1,
    "contract": "pure in-memory editor UI models",
    "data_shapes": ["JSON-compatible values", "dataclasses"],
    "engine_api_surface": False,
    "cli_surface": False,
    "renderer_surface": False,
}

__all__ = [
    "Anchor",
    "BG_RAYGUI_DARK",
    "BUTTON_RADIUS",
    "Button",
    "CONTROL_PADDING_X",
    "CONTROL_PADDING_Y",
    "Container",
    "Control",
    "ControlEvent",
    "ControlEventKind",
    "EDITOR_ACCENT",
    "EDITOR_ACCENT_HOVER",
    "EDITOR_BG",
    "EDITOR_BORDER",
    "EDITOR_BORDER_HOVER",
    "EDITOR_DANGER",
    "EDITOR_PANEL",
    "EDITOR_PANEL_ALT",
    "EDITOR_PANEL_HEADER",
    "EDITOR_SUCCESS",
    "EDITOR_TEXT",
    "EDITOR_TEXT_DISABLED",
    "EDITOR_TEXT_MUTED",
    "EDITOR_WARNING",
    "EditTransaction",
    "EditorTheme",
    "EntityLike",
    "FONT_SIZE_LG",
    "FONT_SIZE_MD",
    "FONT_SIZE_SM",
    "FocusManager",
    "HBoxContainer",
    "ICON_SIZE_MD",
    "ICON_SIZE_SM",
    "InspectorGroup",
    "InspectorModel",
    "Label",
    "LayoutDirection",
    "Margin",
    "PANEL_PADDING",
    "PANEL_RADIUS",
    "Panel",
    "PropertyDescriptor",
    "PropertyEditResult",
    "PropertyKind",
    "PropertyValue",
    "RGBA",
    "ROW_HEIGHT",
    "Rect",
    "SPLITTER_WIDTH",
    "ScrollContainer",
    "Size",
    "TAB_HEIGHT",
    "TOOLBAR_HEIGHT",
    "TextureRect",
    "TreeModel",
    "TreeNode",
    "UI_CORE_CONTRACT",
    "UNITY_DARK",
    "VBoxContainer",
    "WidgetResult",
    "WidgetState",
    "WidgetVisualState",
    "WorldLike",
    "build_inspector_model_from_dict",
    "clamp_rect",
    "filter_nodes",
    "filter_visible_rows",
    "get_entity_type",
    "get_type_icon",
    "infer_property_kind",
    "inset_rect",
    "int_to_rgba",
    "is_dark_theme",
    "lerp_color",
    "matches_search",
    "rect_contains",
    "resolve_visual_state",
    "rgba",
    "rgba_to_hex",
    "rgba_to_int",
    "split_bottom",
    "split_left",
    "split_right",
    "split_top",
    "theme_to_raygui_map",
    "with_alpha",
]
