"""Pure editor UI core namespace.

This package contains serializable, renderer-independent editor UI models and
helpers. It must not import pyray or impure ``engine.editor.ui`` modules.
"""

from engine.editor.ui_core.colors import (
    int_to_rgba,
    is_dark_theme,
    lerp_color,
    rgba,
    rgba_to_hex,
    rgba_to_int,
    with_alpha,
)
from engine.editor.ui_core.controls import (
    Anchor,
    Button,
    ComboBoxModel,
    ConsoleCommandResult,
    ConsoleControlModel,
    Container,
    ContextMenuItem,
    ContextMenuManager,
    ContextMenuModel,
    Control,
    ControlEvent,
    ControlEventKind,
    DropdownModel,
    DropdownOption,
    FocusManager,
    HBoxContainer,
    Label,
    LayoutDirection,
    LogEntry,
    Margin,
    Panel,
    PopupManager,
    PopupModel,
    ScrollContainer,
    Size,
    TextInput,
    TextureRect,
    VBoxContainer,
    alert_popup,
    confirm_popup,
    context_menu_from_tuples,
    yes_no_popup,
)
from engine.editor.ui_core.dock_rects import DockRects, RectTuple, compute_dock_rects
from engine.editor.ui_core.docking import DockArea, DockLayout, DockSplit, dock_node_from_dict, normalize_ratio
from engine.editor.ui_core.geometry import (
    Rect,
    clamp_rect,
    inset_rect,
    rect_contains,
    split_bottom,
    split_left,
    split_right,
    split_top,
)
from engine.editor.ui_core.icon_names import (
    ICON_ANIMATION,
    ICON_ARROW_DOWN,
    ICON_ARROW_UP,
    ICON_AUDIO,
    ICON_CAMERA,
    ICON_CANVAS,
    ICON_CHECK,
    ICON_CHEVRON_LEFT,
    ICON_CHEVRON_RIGHT,
    ICON_CLOSE,
    ICON_COLLIDER,
    ICON_COMPONENT,
    ICON_CONSOLE,
    ICON_COPY,
    ICON_ENTITY,
    ICON_EXPORT,
    ICON_FOLDER,
    ICON_GEAR,
    ICON_LIGHT,
    ICON_MATERIAL,
    ICON_MENU,
    ICON_MINUS,
    ICON_NODE2D,
    ICON_OPEN,
    ICON_PARTICLES,
    ICON_PAUSE,
    ICON_PLAY,
    ICON_PLUS,
    ICON_PREFAB,
    ICON_PROJECT,
    ICON_RIGIDBODY,
    ICON_SAVE,
    ICON_SCENE,
    ICON_SCRIPT,
    ICON_SEARCH,
    ICON_SPRITE,
    ICON_STOP,
    ICON_TERMINAL,
    ICON_TILEMAP,
    ICON_TRASH,
    ICON_UI_BUTTON,
    ICON_UNKNOWN,
    PUBLIC_ICON_NAMES,
)
from engine.editor.ui_core.inspector import (
    InspectorGroup,
    InspectorModel,
    build_inspector_model_from_dict,
    infer_property_kind,
)
from engine.editor.ui_core.property_widgets import (
    EditTransaction,
    PropertyDescriptor,
    PropertyEditResult,
    PropertyKind,
)
from engine.editor.ui_core.protocols import EntityLike, PropertyValue, WorldLike
from engine.editor.ui_core.tokens import (
    BG_RAYGUI_DARK,
    BUTTON_RADIUS,
    CONTROL_PADDING_X,
    CONTROL_PADDING_Y,
    EDITOR_ACCENT,
    EDITOR_ACCENT_HOVER,
    EDITOR_BG,
    EDITOR_BORDER,
    EDITOR_BORDER_HOVER,
    EDITOR_DANGER,
    EDITOR_PANEL,
    EDITOR_PANEL_ALT,
    EDITOR_PANEL_HEADER,
    EDITOR_SUCCESS,
    EDITOR_TEXT,
    EDITOR_TEXT_DISABLED,
    EDITOR_TEXT_MUTED,
    EDITOR_WARNING,
    FONT_SIZE_LG,
    FONT_SIZE_MD,
    FONT_SIZE_SM,
    ICON_SIZE_MD,
    ICON_SIZE_SM,
    PANEL_PADDING,
    PANEL_RADIUS,
    RGBA,
    ROW_HEIGHT,
    SPLITTER_WIDTH,
    TAB_HEIGHT,
    TOOLBAR_HEIGHT,
)
from engine.editor.ui_core.tree_view import (
    TreeModel,
    TreeNode,
    filter_nodes,
    filter_visible_rows,
    get_entity_type,
    get_type_icon,
    matches_search,
)
from engine.editor.ui_core.widget_state import (
    WidgetResult,
    WidgetState,
    WidgetVisualState,
    resolve_visual_state,
)

_THEME_SYMBOLS = {
    "THEME_REGISTRY",
    "UNITY_DARK",
    "UNITY_LIGHT",
    "EditorTheme",
    "ThemeRegistry",
    "get_active_theme",
    "resolve_theme",
    "set_active_theme",
    "theme_to_raygui_map",
}


def __getattr__(name: str):
    if name not in _THEME_SYMBOLS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    import engine.editor.ui_core.theme as _theme

    g = globals()
    for sym in _THEME_SYMBOLS:
        if hasattr(_theme, sym):
            g[sym] = getattr(_theme, sym)
    return g[name]


UI_CORE_CONTRACT = {
    "name": "ui_core",
    "schema_version": 1,
    "contract": "pure in-memory editor UI models",
    "data_shapes": ["JSON-compatible values", "dataclasses"],
    "engine_api_surface": False,
    "cli_surface": False,
    "renderer_surface": False,
}

__all__ = [
    "Anchor",
    "BG_RAYGUI_DARK",
    "BUTTON_RADIUS",
    "Button",
    "CONTROL_PADDING_X",
    "CONTROL_PADDING_Y",
    "Container",
    "ConsoleCommandResult",
    "ConsoleControlModel",
    "Control",
    "ControlEvent",
    "ControlEventKind",
    "ComboBoxModel",
    "ContextMenuItem",
    "ContextMenuManager",
    "ContextMenuModel",
    "DockArea",
    "DockLayout",
    "DockRects",
    "DockSplit",
    "DropdownModel",
    "DropdownOption",
    "EDITOR_ACCENT",
    "EDITOR_ACCENT_HOVER",
    "EDITOR_BG",
    "EDITOR_BORDER",
    "EDITOR_BORDER_HOVER",
    "EDITOR_DANGER",
    "EDITOR_PANEL",
    "EDITOR_PANEL_ALT",
    "EDITOR_PANEL_HEADER",
    "EDITOR_SUCCESS",
    "EDITOR_TEXT",
    "EDITOR_TEXT_DISABLED",
    "EDITOR_TEXT_MUTED",
    "EDITOR_WARNING",
    "EditTransaction",
    "EditorTheme",
    "EntityLike",
    "FONT_SIZE_LG",
    "FONT_SIZE_MD",
    "FONT_SIZE_SM",
    "FocusManager",
    "HBoxContainer",
    "ICON_AUDIO",
    "ICON_ANIMATION",
    "ICON_ARROW_DOWN",
    "ICON_ARROW_UP",
    "ICON_CAMERA",
    "ICON_CANVAS",
    "ICON_CHECK",
    "ICON_CHEVRON_LEFT",
    "ICON_CHEVRON_RIGHT",
    "ICON_CLOSE",
    "ICON_COLLIDER",
    "ICON_COMPONENT",
    "ICON_CONSOLE",
    "ICON_COPY",
    "ICON_ENTITY",
    "ICON_EXPORT",
    "ICON_FOLDER",
    "ICON_GEAR",
    "ICON_SIZE_MD",
    "ICON_SIZE_SM",
    "ICON_LIGHT",
    "ICON_MATERIAL",
    "ICON_MENU",
    "ICON_MINUS",
    "ICON_NODE2D",
    "ICON_OPEN",
    "ICON_PAUSE",
    "ICON_PARTICLES",
    "ICON_PLAY",
    "ICON_PLUS",
    "ICON_PREFAB",
    "ICON_PROJECT",
    "ICON_RIGIDBODY",
    "ICON_SAVE",
    "ICON_SCENE",
    "ICON_SCRIPT",
    "ICON_SEARCH",
    "ICON_SPRITE",
    "ICON_STOP",
    "ICON_TERMINAL",
    "ICON_TILEMAP",
    "ICON_TRASH",
    "ICON_UI_BUTTON",
    "ICON_UNKNOWN",
    "InspectorGroup",
    "InspectorModel",
    "Label",
    "LayoutDirection",
    "LogEntry",
    "Margin",
    "PANEL_PADDING",
    "PANEL_RADIUS",
    "Panel",
    "PopupManager",
    "PopupModel",
    "PropertyDescriptor",
    "PropertyEditResult",
    "PropertyKind",
    "PropertyValue",
    "PUBLIC_ICON_NAMES",
    "RGBA",
    "RectTuple",
    "ROW_HEIGHT",
    "Rect",
    "SPLITTER_WIDTH",
    "ScrollContainer",
    "Size",
    "TAB_HEIGHT",
    "THEME_REGISTRY",
    "ThemeRegistry",
    "TOOLBAR_HEIGHT",
    "TextureRect",
    "TextInput",
    "TreeModel",
    "TreeNode",
    "UI_CORE_CONTRACT",
    "UNITY_DARK",
    "UNITY_LIGHT",
    "VBoxContainer",
    "WidgetResult",
    "WidgetState",
    "WidgetVisualState",
    "WorldLike",
    "alert_popup",
    "build_inspector_model_from_dict",
    "clamp_rect",
    "compute_dock_rects",
    "confirm_popup",
    "context_menu_from_tuples",
    "dock_node_from_dict",
    "filter_nodes",
    "filter_visible_rows",
    "get_entity_type",
    "get_active_theme",
    "get_type_icon",
    "infer_property_kind",
    "inset_rect",
    "int_to_rgba",
    "is_dark_theme",
    "lerp_color",
    "matches_search",
    "normalize_ratio",
    "rect_contains",
    "resolve_visual_state",
    "resolve_theme",
    "set_active_theme",
    "rgba",
    "rgba_to_hex",
    "rgba_to_int",
    "split_bottom",
    "split_left",
    "split_right",
    "split_top",
    "theme_to_raygui_map",
    "with_alpha",
    "yes_no_popup",
]
