from __future__ import annotations

from typing import Any

class Vector2:
    x: float
    y: float

    def __init__(self, x: float = ..., y: float = ...) -> None: ...

class Rectangle:
    x: float
    y: float
    width: float
    height: float

    def __init__(self, x: float = ..., y: float = ..., width: float = ..., height: float = ...) -> None: ...

class Color:
    r: int
    g: int
    b: int
    a: int

    def __init__(self, r: int = ..., g: int = ..., b: int = ..., a: int = ...) -> None: ...

class Camera2D:
    offset: Vector2
    target: Vector2
    rotation: float
    zoom: float

    def __init__(
        self,
        offset: Vector2 | None = ...,
        target: Vector2 | None = ...,
        rotation: float = ...,
        zoom: float = ...,
    ) -> None: ...

class Texture:
    id: int
    width: int
    height: int
    mipmaps: int
    format: int
    texture: Texture

class Image:
    width: int
    height: int
    mipmaps: int
    format: int

class _FFI:
    def new(self, cdecl: str, init: Any = ...) -> list[Any]: ...

ffi: _FFI

WHITE: Color
BLACK: Color
BLANK: Color
RED: Color
GREEN: Color
BLUE: Color
YELLOW: Color
ORANGE: Color
SKYBLUE: Color
GRAY: Color
LIGHTGRAY: Color
DARKGRAY: Color
PINK: Color
PURPLE: Color
VIOLET: Color
MAGENTA: Color
GOLD: Color
LIME: Color
BROWN: Color
DARKBLUE: Color
MAROON: Color
DARKPURPLE: Color
BEIGE: Color
LAVENDER: Color
RAYWHITE: Color

MOUSE_BUTTON_LEFT: int
MOUSE_BUTTON_RIGHT: int
MOUSE_BUTTON_MIDDLE: int

def gen_image_color(width: int, height: int, color: Any) -> Image: ...
def image_draw_rectangle(image: Image, x: int, y: int, width: int, height: int, color: Any) -> None: ...
def export_image(image: Image, path: str) -> bool: ...
def load_image(path: str) -> Image: ...
def is_image_valid(image: Any) -> bool: ...
def load_image_colors(image: Image) -> list[Color]: ...
def unload_image_colors(colors: Any) -> None: ...
def unload_image(image: Any) -> None: ...
def load_texture(path: str) -> Texture: ...
def load_texture_from_image(image: Image) -> Texture: ...
def load_render_texture(width: int, height: int) -> Texture: ...
def load_image_from_texture(texture: Any) -> Image: ...
def image_flip_vertical(image: Any) -> Any: ...
def unload_texture(texture: Any) -> None: ...
def unload_render_texture(texture: Any) -> None: ...
def measure_text_ex(*args: Any, **kwargs: Any) -> Vector2: ...
def check_collision_point_rec(point: Any, rect: Any) -> bool: ...
def gui_toggle(*args: Any, **kwargs: Any) -> bool: ...
def gui_text_box(*args: Any, **kwargs: Any) -> bool: ...
def gui_text_box_multi(*args: Any, **kwargs: Any) -> bool: ...
def get_mouse_position() -> Vector2: ...
def get_mouse_wheel_move() -> float: ...
def get_screen_to_world_2d(position: Any, camera: Any) -> Vector2: ...
def is_window_ready() -> bool: ...
def is_window_fullscreen() -> bool: ...
def get_current_monitor() -> int: ...
def get_monitor_width(monitor: int) -> int: ...
def get_monitor_height(monitor: int) -> int: ...
def get_screen_width() -> int: ...
def get_screen_height() -> int: ...
def get_render_width() -> int: ...
def get_render_height() -> int: ...
def get_fps() -> int: ...
def get_time() -> float: ...
def get_glyph_index(*args: Any, **kwargs: Any) -> int: ...
def get_codepoint(*args: Any, **kwargs: Any) -> int: ...
def get_codepoints(text: str) -> list[int]: ...
def text_length(text: str) -> int: ...
def begin_mode_2d(*args: Any, **kwargs: Any) -> None: ...
def end_mode_2d(*args: Any, **kwargs: Any) -> None: ...
def begin_texture_mode(*args: Any, **kwargs: Any) -> None: ...
def end_texture_mode(*args: Any, **kwargs: Any) -> None: ...
def begin_drawing(*args: Any, **kwargs: Any) -> None: ...
def end_drawing(*args: Any, **kwargs: Any) -> None: ...
def clear_background(*args: Any, **kwargs: Any) -> None: ...
def set_window_size(*args: Any, **kwargs: Any) -> None: ...
def set_config_flags(*args: Any, **kwargs: Any) -> None: ...
def init_window(*args: Any, **kwargs: Any) -> None: ...
def toggle_fullscreen(*args: Any, **kwargs: Any) -> None: ...
def close_window(*args: Any, **kwargs: Any) -> None: ...
def set_target_fps(*args: Any, **kwargs: Any) -> None: ...
def draw_text(*args: Any, **kwargs: Any) -> None: ...
def draw_line(*args: Any, **kwargs: Any) -> None: ...
def draw_line_ex(*args: Any, **kwargs: Any) -> None: ...
def draw_circle(*args: Any, **kwargs: Any) -> None: ...
def draw_circle_lines(*args: Any, **kwargs: Any) -> None: ...
def draw_rectangle(*args: Any, **kwargs: Any) -> None: ...
def draw_rectangle_rec(*args: Any, **kwargs: Any) -> None: ...
def draw_rectangle_lines(*args: Any, **kwargs: Any) -> None: ...
def draw_rectangle_lines_ex(*args: Any, **kwargs: Any) -> None: ...
def draw_triangle(*args: Any, **kwargs: Any) -> None: ...
def draw_texture(*args: Any, **kwargs: Any) -> None: ...
def draw_texture_pro(*args: Any, **kwargs: Any) -> None: ...
def begin_scissor_mode(*args: Any, **kwargs: Any) -> None: ...
def end_scissor_mode(*args: Any, **kwargs: Any) -> None: ...
def is_mouse_button_pressed(*args: Any, **kwargs: Any) -> bool: ...
def is_mouse_button_down(*args: Any, **kwargs: Any) -> bool: ...
def is_mouse_button_released(*args: Any, **kwargs: Any) -> bool: ...
def is_key_pressed(*args: Any, **kwargs: Any) -> bool: ...
def is_key_down(*args: Any, **kwargs: Any) -> bool: ...
def gui_button(*args: Any, **kwargs: Any) -> bool: ...
def get_window_position() -> Vector2: ...
def load_font_default() -> object: ...

def __getattr__(name: str) -> Any: ...
